# Generated by Django 2.2.16 on 2021-01-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0053_auto_20200510_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='phone'),
        ),
    ]
