# Generated by Django 2.2.16 on 2021-01-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0053_auto_20200510_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
