# Generated by Django 2.2.16 on 2021-01-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0053_auto_20200510_1634'),
    ]

    operations = [
    ]
