# Generated by Django 2.2.16 on 2021-01-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_auth', '0054_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
              model_name="User", 
              name="phone", 
              field=models.CharField(
                  max_length=20, 
                  blank=True, 
                  verbose_name='phone number')
        ),
    ]
