# Generated by Django 2.2.16 on 2021-01-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openbook_moderation', '0014_auto_20191205_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationcategory',
            name='order',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
